### ISSUE TITLE
How to evaluate DROID SLAM ?

### ISSUE THREAD

**Issue by lbg030** [cvg/nicer-slam#11]
I have question for Evaluation.

As far as I know, DROID SLAM has a Scale problem.
Nicerslam and scale won't fit, how did you proceed with the evaluation?
Did you manualy match it through cloudcompare and evaluate it?

**Comment by Zzh2000** [comment]
For monocular methods, the scale is not consistent between different methods. We always transform the coordinate to the gt coordinate. We first do the coarse alignment by using the sim3 matrix from the alignment of trajectory with gt trajectory, then we refine the matching using cloudcompare.
