### ISSUE TITLE
About scene bound in nicer-slam

### ISSUE THREAD

**Issue by 00Haocheng** [cvg/nicer-slam#13]
Thanks for sharing this excellent work; But there's one thing I don't understand; In NICE-SLAM, the bound of the scene is pre-set according to different data. Why is the bound of the scene in nicer-slam always -1 to 1? Will this make the sampling points be affected?

**Comment by Zzh2000** [comment]
Hi, thanks for your interest in our work. We directly follow VolSDF/MonoSDF's way of parameterization by scaling the whole scene into -1 to 1. It is basically because of the codebase, and should not affect the performance.

**Comment by 00Haocheng** [comment]
Thank you for your replica!
