### ISSUE TITLE
Training stuck

### ISSUE THREAD

**Issue by Davidyao99** [cvg/nicer-slam#2]
Great Work!

I am running the demo for this repo, but my training seems to be stuck. 

I am using a A6000 GPU, so I added `elif 'A6000' in device:
    device='A6000'` in "./code/hashencoder/backend.py".

When I run with "python training/exp_runner.py --conf confs/runconf_demo_1.conf",, program outputs `build_directory ./tmp_build_A6000/` and nothing seems to be running after that. Any idea why? 

Thank you!

**Comment by Zzh2000** [comment]
Hi, thanks for your interest in our work!
You could check exactly which command is running for a long time.
I suspect might come from the building of the module. Please check if you have gcc/CUDA/cudnn installed.
The hashencoder is adapted from MonoSDF and I think is originally from torch-ngp, for more details you could also check their repository and their issues.
Good luck!
