### ISSUE TITLE
Running in online mode

### ISSUE THREAD

**Issue by nirmalsnair** [cvg/nicer-slam#5]
Hi, thanks for sharing the code.

I'm wondering if there's a way to execute this in online mode, as intended for SLAM operation?

**Comment by Zzh2000** [comment]
Hi, thanks for your interest in our work.
Since our work is an initial exploration of monocular implicit SLAM and cannot do real-time, we do not have this online mode available.

**Comment by nirmalsnair** [comment]
Okay, thanks!
