### ISSUE TITLE
关于室外数据集的表现

### ISSUE THREAD

**Issue by james201011071** [cvg/nicer-slam#6]
你好，非常感谢分享这个工作。我想知道像这种神经隐式表达的SLAM系统能否应用在室外数据集，比如KITTI数据？我看目前的一些架构比如splaTAM,GS-SLAM这些都没提及到室外数据集的表现，或者您觉得这些框架应用到室外数据会有什么问题，需要做哪些改进呢？

**Comment by Zzh2000** [comment]
你好！感谢对我们工作的兴趣。PIN-SLAM, LONER, NeRF-LOAM等文章可以应用在室外，不过输入需要LIDAR，没有纯RGB的。splaTAM,GS-SLAM如果是RGB-D输入我觉得可以试试在室外数据集的表现，应该不会特别差。
