### ISSUE TITLE
Can not run visualization: GLFW Error: X11

### ISSUE THREAD

**Issue by be-hd** [cvg/nicer-slam#8]
I got this error when running the visualizer.py  script: 
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW 
I run on a remote GPU machine.  Is there a way to save the Open 3D rendering into file instead of creating display window?

Thank you.

**Comment by Zzh2000** [comment]
Hi, 
if you are working on a remote GPU machine, then it would be quite hard to use Open3D visualization. I would suggest you run the visualization on a desktop. The visualization does not require powerful GPU at all.
