### ISSUE TITLE
What's the actual input to NICER-SLAM?

### ISSUE THREAD

**Issue by be-hd** [cvg/nicer-slam#9]
I have a monocular video, what are the step to run NICER-SLAM to get to the final output of the demo video with 3D map and camera trajectory? 
Looks like NICER-SLAM requires not only monocular video/frames as an input, but also requires: 

1. COLMAP output (cameras.bin, images,bin, points3D.bin) --> How to generate these given a monocular video? What are these values stand for?
2. Depth info (monocular depth estimation using a 3rd party package)
3. Normal info (monocular normal estimation using a 3rd party package)
4. Optical flow (estimation using a 3rd party package)
5. Camera pose???
6. Anything else?

Then how the accuracy of these input impact the final output of NICER-SLAM?

Thank you.

**Comment by OnHaDe** [comment]
You are correct, despite the implication of the paper you need more data than the simple image sequence. These are only used to calculate the loss and not as direct inputs as far as I can tell. 

1. Get COLMAP. Put the video frames in a directory of your choice and run something like:
`colmap automatic_reconstructor --workspace_path /your/workspace/path --image_path /your/dataset/frames --vocab_tree path/to/vocab_tree.bin --single_camera 1 --num_threads 12`
The last three arguments are dependant on your circumstances, you can refer to the COLMAP documentation for that
2 - 4. Are handled by the preprocessing scripts (presuming you set up the conda environments)
5. The COLMAP output includes the camera poses. They are transformed to a new format in the preprocessing scripts.
6. That's all

**Comment by Zzh2000** [comment]
The COLMAP and the camera pose are not a necessity for running NICER-SLAM. You can check the code and find that they are used for getting the scene bound and normalizing the scene scale to -1 to 1 to satisfy the VolSDF/MonoSDF code base. The gt poses are good for debugging (e.g. gt_cam=True meaning debugging by giving every camera gt pose) and they are not involved in the tracking/mapping process.

**Comment by Golbstein** [comment]
and what about the depth and normal inputs? You've depth\normal weights in your loss
